### ISSUE TITLE
colouring subgroups and summary effects

### ISSUE THREAD

**Issue by ciaranodriscoll** [Mkossmeier/metaviz#1]
Dear Michael, 

I am trying to colour studies by group. However, I get the following error. I presume it's because I am including the summaries. Is there a way to colour both within the forest plot? 

Error: Aesthetics must be either length 1 or the same as the data (24): colour, fill, size
In addition: Warning message:
In if (col %in% c("Blues", "Greys", "Oranges", "Greens", "Reds",  :
  the condition has length > 1 and only the first element will be used

forest <- viz_forest(x = dat[, c("d", "se")], group = dat$Drug, type = "standard", variant = "thick", 
                     method = "REML", study_labels = dat$study_name, summary_label = c("Summary (Alcohol)", 
                    "Summary (Cannabis)","Summary (Ecstacy)","Summary (Methamphetamine)", "Opiate", "Summary(Tobacco)"),
                     confidence_level = 0.95, text_size = 3, tick_col = "firebrick",
                     xlab = "Cohen d", annotate_CI = TRUE, study_table = study_table,
                     summary_table = NULL, table_headers = c("Study","Drug (m/sd/n)", "Control (m/sd/n)"), table_layout = NULL, 
                    col = c("goldenrod4", "steelblue4", "green", "plum", "cadetblue")[dat$Drug])

**Comment by Mkossmeier** [comment]
Thanks for opening an issue. A feature to individually color studies and/or summary effects by supplying a vector of colors is now implemented in version 0.3.0 (currently on github only; should be on CRAN by end of January, 2019).

Michael
