### ISSUE TITLE
Funnel outside the plotting area in funnel_viz()

### ISSUE THREAD

**Issue by lnalborczyk** [Mkossmeier/metaviz#2]
Hi Michael,

thank you very much for putting together this package, it's very helpful.

I have used `funnel_viz()` recently but I've been a bit surprised by the fact that the funnel sometimes appears outside the plotting area. Is it intended behaviour ?

Here is a short reproducible example:

```
library(metaviz)
library(metafor)

# create the funnel plot from a metafor model (for convenience)
data <- data.frame(g = rnorm(1e2), vi = rexp(1e2) )
res <- rma(yi = g, vi, data = data, measure = "GEN")

# metafor funnel plot
funnel(res)

# ggplot2 metaviz funnel plot
viz_funnel(
    x = res, method = "REML",
    contours = TRUE, sig_contours = FALSE,
    contours_col = "Greys", xlab = "Observed outcome"
    )

```

I have managed to reproduce the output from `metafor::funnel()` by amending your code. I have just made a minor change to the `viz_funnel()` function (available [here](https://github.com/Mkossmeier/metaviz/blob/master/R/viz_funnel.R)) from line 356 to 260). Here is what I changed (I simply commented out a few things).

```
funneldata <- data.frame(
                x = c(
                    summary_es - stats::qnorm(0.975) * sqrt(max_se^2 + summary_tau2),
                    summary_es,# - stats::qnorm(0.975) * sqrt(summary_tau2),
                    summary_es,# + stats::qnorm(0.975) * sqrt(summary_tau2),
                    summary_es + stats::qnorm(0.975) * sqrt(max_se^2 + summary_tau2)
                    ),
                
                y = c(max_se, 0, 0, max_se)
                
                )
```

Hope this can be useful :-)

**Comment by Mkossmeier** [comment]
Hi,

thanks for opening an issue and providing a reproducible example - much appreciated! Currently, confidence contours (the classic funnel) correspond to the underlying meta-analytic method chosen (via the method argument). For a random effects model, these contours do not necessarily converge to a single point at the top of the funnel plot (for a standard error of zero). If there is an excess of between study variance (heterogeneity), 95% of all (hypothetical) studies with a standard error of 0 are expected to fall within the mean effect +/- 1.96 times tau squared (if we assume normality and parameters as known). So, it's not really a bug, but intended behavior incorporating the underlying meta-analytic model.

If you want to show the summary effect of a random effects model, but the classic fixed effect (triangle shaped) contours, I suggest using method = "FE" in viz_funnel and adding an additional line for the estimated summary effect from the random effects model using ggplot2 syntax:

viz_funnel(
  x = res, method = "FE",
  contours = TRUE, sig_contours = FALSE,
  contours_col = "Greys", xlab = "Observed outcome") + 
ggplot2::geom_vline(xintercept = res$b, linetype = "dashed") 

Hope this helps!
Michael

**Comment by lnalborczyk** [comment]
Hi Michael,

mea culpa and thank you for your detailed and very informative answer :-)
