### ISSUE TITLE
"contours" and "sig_contours" overlap

### ISSUE THREAD

**Issue by ghost** [Mkossmeier/metaviz#5]
Hello, 
Thank you for your useful package first and I have a doubt.
When I tried to draw a funnel plot using viz_funnel(), I saw the funnel plot contours and the significance contours overlapped with commands contours=T and sig_contours=T. On the other hand, the funnel plot contours were symmetrical at summarized effect size but the significance contours were symmetrical at zero. So these two contours seem garbled. Is it a normal situation with my wrong understanding or a Bug?

**Comment by Mkossmeier** [comment]
Hello Qingys,

thanks for your message and sorry for the rather late response.  This is intended behavior and not a bug. 

- Significance contours (sig_contours = T) are centered at zero and show which effects are significantly different from zero. They are primarly used to check if asymmetry in the funnel plot is driven by statistical significance. 

- Confidence contours (contours = T) are centered at the summary effect and show where we expect studies to fall with a probability of 95% if the specified model is correct. They are primalry used to detect potential outliers or heterogeneity.

Best,
Michael

**Comment by ghost** [comment]
Hello Michael, 

Thank you very much for your response and I think I have a further understanding about funnel plot. 

In addition, I have another question for forest plot. I found that the argument "x" in viz_forest() can be a matrix with the effect sizes and their standard errors. If I do not have corresponding standard errors but rather their corresponding 95%CrI, can I use this function now? Is there any method to handle this? The reason for this requirement is that we always tend to use 95% credible interval to interpret the results but not the Naive SE or Time-series SE when we used Bayesian method along with MCMC.

**Comment by Mkossmeier** [comment]
Currently it is not possible to supply confidence or credibility intervals directly to function viz_forest(). However, this is something I plan to implement in the near future.
